### ISSUE TITLE
Fix view logic for rendering delegation information

### ISSUE THREAD

**Issue by davefrey** [liquidvotingio/decidim-liquidvoting#14]
We should conditionally render the delegation _functionality_ for logged-in useres only, since it depends on `current_user.email`. 

Additionally maybe there is a question of when to render delegation _information_.

Context for this table is the page of a specific proposal, which may or may not have associated delegation(s).

Current User | Delegation | Show that delegation info (RO) | Show delegation info + buttons
------------- | -------- | -------- | -------
(none)            | (none)   | n/a          | nope 🙅‍♀️
(none)            | A -> B   | maybe? (*)  | nope 🙅‍♀️
A                     | A -> B   | YES        | YES
B                     | A -> B   | nope 🙅‍♀️  | YES
C                     | A -> B   | nope 🙅‍♀️  | YES

(*) probably not though, because there are 0..N

**Comment by davefrey** [comment]
The fourth case (I'm B, and a delegation A->B exists) is a little weird to me, I have no way to know how many delegations I'm voting for. Maybe a "(my vote will also represent NN delegators)" message

**Comment by oliverbarnes** [comment]
> We should conditionally render the delegation functionality for logged-in users only, since it depends on current_user.email

Definitely, well spotted 👍 

> Additionally maybe there is a question of when to render delegation information.

Thanks for laying it out on that table, it describes the different scenarios nicely. The question of whether to show delegation information is a thorny one, as it can have privacy and also political implications - like popular delegates getting more delegations simply because of their current number of delegations. Network effects etc. 

So I think beyond the first and third cases (guests viewing proposals, and current user viewing their own delegation on a proposal to somebody else), it should be configurable so a client organization can decide on how handle this.

What do you think of extracting this into its own issue? Seems to me showing/hiding delegation creation/deletion and viewing delegation information (count, delegation graph) are two discrete things to be handled in different PRs. This last one might be multiple PRs, in fact
